<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "image_async_process"
 *
 * Auto generated by Extension Builder 2016-02-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Asynchronous image processing',
	'description' => 'Speeds up rendering time for a page with many pictures.',
	'category' => 'fe',
	'author' => 'R3H6',
	'author_email' => 'r3h6@outlook.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);